whitelist_rules:
  - cyclomatic_complexity
  - line_length  # warning: 110
  - overridden_super_call
  - function_parameter_count #  warning: 5, error: 8
  - function_body_length # warning: 40, error: 100
  - explicit_init # dont explicit call .init(..)
  - mark # correct // MARK: statements
  - opening_brace # space between opening brace and on same line with brackets
  - return_arrow_whitespace
  - colon # space added to right-handside of colon	
excluded:
  - Carthage
  - .build

cyclomatic_complexity: warning
force_cast: warning
line_length: 120
file_length:
  warning: 300
  error: 650

reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji)
